---
exclude: '^docs/conf.py'
default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: ["commit"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=650']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=auto']  # use 'lf' to enforce *nix or 'crlf' for Windows
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.2.0  # stable 0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--show-source']
        additional_dependencies: [wemake-python-styleguide]

  - repo: local
    hooks:
      - id: encryption-check
        name: Ansible Vault Encryption Check
        description: Checks that vault files are encrypted
        entry: /usr/local/bin/encryption-check.sh
        files: ((^|/)vault|vault.y[a]{0,1}ml$|.vault$)
        language: script
      - id: commit-msg
        name: conventional commit messages
        language: pygrep
        # yamllint disable-line rule:line-length
        entry: '^(chore|test|feat|fix|build|docs|refactor)!?: ((?!.*(ing))(?!.*(ed))).*$'
        args: [--multiline, --negate]
        stages: [commit-msg]
